// <auto-generated />
using System;
using Condo.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Condo.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CondoDbContext))]
    [Migration("20260615233441_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Condo.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Email")
                        .IsUnique()
                        .HasFilter("[CompanyId] IS NOT NULL");

                    b.ToTable("ApplicationUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b781a1aa-6f3d-46d3-8f78-72e7a0000001"),
                            CreatedAtUtc = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "superadmin@codexa.local",
                            FullName = "Super Admin Codexa",
                            IsActive = true,
                            IsDeleted = false,
                            MustChangePassword = true,
                            PasswordHash = "123456",
                            Role = "SuperAdmin",
                            UpdatedAtUtc = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b781a1aa-6f3d-46d3-8f78-72e7a0000003"),
                            CompanyId = new Guid("b781a1aa-6f3d-46d3-8f78-72e7a0000002"),
                            CreatedAtUtc = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@codexa.local",
                            FullName = "Admin Empresa Demo",
                            IsActive = true,
                            IsDeleted = false,
                            MustChangePassword = true,
                            PasswordHash = "123456",
                            Role = "CompanyAdmin",
                            UpdatedAtUtc = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b781a1aa-6f3d-46d3-8f78-72e7a0000009"),
                            CompanyId = new Guid("b781a1aa-6f3d-46d3-8f78-72e7a0000002"),
                            CreatedAtUtc = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "manager@codexa.local",
                            FullName = "Manager Martinica",
                            IsActive = true,
                            IsDeleted = false,
                            MustChangePassword = true,
                            PasswordHash = "123456",
                            Role = "BuildingManager",
                            UpdatedAtUtc = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Condo.Domain.Entities.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CondominiumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CondominiumId");

                    b.HasIndex("CompanyId", "Code")
                        .IsUnique();

                    b.ToTable("Buildings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b781a1aa-6f3d-46d3-8f78-72e7a0000005"),
                            Address = "Asuncion, Paraguay",
                            Code = "MART-01",
                            CompanyId = new Guid("b781a1aa-6f3d-46d3-8f78-72e7a0000002"),
                            CondominiumId = new Guid("b781a1aa-6f3d-46d3-8f78-72e7a0000004"),
                            CreatedAtUtc = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Edificio Martinica",
                            UpdatedAtUtc = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Condo.Domain.Entities.BuildingExpense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DistributionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("ExpenseDate")
                        .HasColumnType("date");

                    b.Property<Guid>("ExpensePeriodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TargetUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ExpensePeriodId");

                    b.HasIndex("TargetUnitId");

                    b.HasIndex("BuildingId", "ExpensePeriodId", "ExpenseDate");

                    b.ToTable("BuildingExpenses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b781a1aa-6f3d-46d3-8f78-72e7a0000014"),
                            Amount = 1200000m,
                            BuildingId = new Guid("b781a1aa-6f3d-46d3-8f78-72e7a0000005"),
                            Category = "Cleaning",
                            CompanyId = new Guid("b781a1aa-6f3d-46d3-8f78-72e7a0000002"),
                            CreatedAtUtc = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Servicio mensual de limpieza de areas comunes",
                            DistributionType = "ByCoefficient",
                            ExpenseDate = new DateOnly(2026, 6, 5),
                            ExpensePeriodId = new Guid("b781a1aa-6f3d-46d3-8f78-72e7a0000011"),
                            IsDeleted = false,
                            Notes = "Gasto semilla para pruebas del modulo de gastos del edificio.",
                            SupplierName = "Limpieza Integral SA",
                            UpdatedAtUtc = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Condo.Domain.Entities.BuildingIncome", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ExpensePeriodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("IncomeDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ExpensePeriodId");

                    b.HasIndex("BuildingId", "ExpensePeriodId", "IncomeDate");

                    b.ToTable("BuildingIncomes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b781a1aa-6f3d-46d3-8f78-72e7a0000015"),
                            Amount = 350000m,
                            BuildingId = new Guid("b781a1aa-6f3d-46d3-8f78-72e7a0000005"),
                            Category = "OperationalFund",
                            CompanyId = new Guid("b781a1aa-6f3d-46d3-8f78-72e7a0000002"),
                            CreatedAtUtc = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Compensacion de fondo operativo del periodo",
                            ExpensePeriodId = new Guid("b781a1aa-6f3d-46d3-8f78-72e7a0000011"),
                            IncomeDate = new DateOnly(2026, 6, 8),
                            IsDeleted = false,
                            Notes = "Ingreso semilla para pruebas del modulo de ingresos del edificio.",
                            UpdatedAtUtc = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Condo.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b781a1aa-6f3d-46d3-8f78-72e7a0000002"),
                            CreatedAtUtc = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Codexa Administradora Demo",
                            Slug = "codexa-admin-demo",
                            UpdatedAtUtc = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Condo.Domain.Entities.Condominium", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Code")
                        .IsUnique();

                    b.ToTable("Condominiums");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b781a1aa-6f3d-46d3-8f78-72e7a0000004"),
                            Address = "Asuncion, Paraguay",
                            Code = "CMZ-01",
                            CompanyId = new Guid("b781a1aa-6f3d-46d3-8f78-72e7a0000002"),
                            CreatedAtUtc = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Condominio Martinez",
                            UpdatedAtUtc = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Condo.Domain.Entities.ExpenseCharge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ChargeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Concept")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ExpensePeriodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLateFee")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SourceBuildingExpenseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SourceSettlementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ExpensePeriodId");

                    b.HasIndex("SourceBuildingExpenseId");

                    b.HasIndex("SourceSettlementId");

                    b.HasIndex("UnitId");

                    b.ToTable("ExpenseCharges");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b781a1aa-6f3d-46d3-8f78-72e7a0000012"),
                            Amount = 850000m,
                            ChargeType = "Ordinary",
                            CompanyId = new Guid("b781a1aa-6f3d-46d3-8f78-72e7a0000002"),
                            Concept = "Expensa ordinaria",
                            CreatedAtUtc = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpensePeriodId = new Guid("b781a1aa-6f3d-46d3-8f78-72e7a0000011"),
                            IsDeleted = false,
                            IsLateFee = false,
                            Notes = "Cargo semilla para pruebas del modulo financiero.",
                            UnitId = new Guid("b781a1aa-6f3d-46d3-8f78-72e7a0000006"),
                            UpdatedAtUtc = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Condo.Domain.Entities.ExpensePeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("BuildingId", "Year", "Month")
                        .IsUnique();

                    b.ToTable("ExpensePeriods");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b781a1aa-6f3d-46d3-8f78-72e7a0000011"),
                            BuildingId = new Guid("b781a1aa-6f3d-46d3-8f78-72e7a0000005"),
                            CompanyId = new Guid("b781a1aa-6f3d-46d3-8f78-72e7a0000002"),
                            CreatedAtUtc = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateOnly(2026, 7, 10),
                            EndDate = new DateOnly(2026, 6, 30),
                            IsDeleted = false,
                            Month = 6,
                            Name = "Junio 2026",
                            Notes = "Periodo inicial de expensas para pruebas del modulo financiero.",
                            StartDate = new DateOnly(2026, 6, 1),
                            Status = "Draft",
                            UpdatedAtUtc = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Year = 2026
                        });
                });

            modelBuilder.Entity("Condo.Domain.Entities.ExpenseSettlement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ExpensePeriodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ExtraordinaryAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GeneratedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("NetCommonAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("PublishedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ReserveFundAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalBuildingExpenses")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalBuildingIncomes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("BuildingId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ExpensePeriodId")
                        .IsUnique();

                    b.HasIndex("GeneratedByUserId");

                    b.HasIndex("PublishedByUserId");

                    b.ToTable("ExpenseSettlements");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b781a1aa-6f3d-46d3-8f78-72e7a0000016"),
                            BuildingId = new Guid("b781a1aa-6f3d-46d3-8f78-72e7a0000005"),
                            CompanyId = new Guid("b781a1aa-6f3d-46d3-8f78-72e7a0000002"),
                            CreatedAtUtc = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpensePeriodId = new Guid("b781a1aa-6f3d-46d3-8f78-72e7a0000011"),
                            ExtraordinaryAmount = 0m,
                            GeneratedAtUtc = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GeneratedByUserId = new Guid("b781a1aa-6f3d-46d3-8f78-72e7a0000009"),
                            IsDeleted = false,
                            NetCommonAmount = 850000m,
                            ReserveFundAmount = 0m,
                            Status = "Calculated",
                            TotalBuildingExpenses = 1200000m,
                            TotalBuildingIncomes = 350000m,
                            UpdatedAtUtc = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Condo.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ExpensePeriodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ExpensePeriodId");

                    b.HasIndex("UnitId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b781a1aa-6f3d-46d3-8f78-72e7a0000013"),
                            Amount = 250000m,
                            CompanyId = new Guid("b781a1aa-6f3d-46d3-8f78-72e7a0000002"),
                            CreatedAtUtc = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpensePeriodId = new Guid("b781a1aa-6f3d-46d3-8f78-72e7a0000011"),
                            IsDeleted = false,
                            Method = "BankTransfer",
                            Notes = "Pago parcial semilla para pruebas del modulo financiero.",
                            PaymentDate = new DateOnly(2026, 6, 15),
                            Reference = "TRX-0001",
                            UnitId = new Guid("b781a1aa-6f3d-46d3-8f78-72e7a0000006"),
                            UpdatedAtUtc = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Condo.Domain.Entities.Resident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "DocumentNumber")
                        .IsUnique();

                    b.ToTable("Residents");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b781a1aa-6f3d-46d3-8f78-72e7a0000007"),
                            CompanyId = new Guid("b781a1aa-6f3d-46d3-8f78-72e7a0000002"),
                            CreatedAtUtc = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DocumentNumber = "1234567",
                            Email = "residente@codexa.local",
                            FullName = "Residente Demo",
                            IsActive = true,
                            IsDeleted = false,
                            IsOwner = true,
                            PhoneNumber = "0991000000",
                            UpdatedAtUtc = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Condo.Domain.Entities.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Coefficient")
                        .HasColumnType("decimal(18,6)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Floor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("BuildingId", "Code")
                        .IsUnique();

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b781a1aa-6f3d-46d3-8f78-72e7a0000006"),
                            BuildingId = new Guid("b781a1aa-6f3d-46d3-8f78-72e7a0000005"),
                            Code = "A-101",
                            Coefficient = 1.000000m,
                            CompanyId = new Guid("b781a1aa-6f3d-46d3-8f78-72e7a0000002"),
                            CreatedAtUtc = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = "1",
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedAtUtc = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Condo.Domain.Entities.UnitResident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ResidentId");

                    b.HasIndex("UnitId", "ResidentId", "StartDate")
                        .IsUnique();

                    b.ToTable("UnitResidents");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b781a1aa-6f3d-46d3-8f78-72e7a0000008"),
                            CompanyId = new Guid("b781a1aa-6f3d-46d3-8f78-72e7a0000002"),
                            CreatedAtUtc = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsPrimary = true,
                            ResidentId = new Guid("b781a1aa-6f3d-46d3-8f78-72e7a0000007"),
                            StartDate = new DateOnly(2026, 1, 1),
                            UnitId = new Guid("b781a1aa-6f3d-46d3-8f78-72e7a0000006"),
                            UpdatedAtUtc = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Condo.Domain.Entities.UserBuildingAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("ApplicationUserId", "BuildingId")
                        .IsUnique();

                    b.ToTable("UserBuildingAccesses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b781a1aa-6f3d-46d3-8f78-72e7a0000010"),
                            ApplicationUserId = new Guid("b781a1aa-6f3d-46d3-8f78-72e7a0000009"),
                            BuildingId = new Guid("b781a1aa-6f3d-46d3-8f78-72e7a0000005"),
                            CompanyId = new Guid("b781a1aa-6f3d-46d3-8f78-72e7a0000002"),
                            CreatedAtUtc = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedAtUtc = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Condo.Domain.Entities.ApplicationUser", b =>
                {
                    b.HasOne("Condo.Domain.Entities.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Condo.Domain.Entities.Building", b =>
                {
                    b.HasOne("Condo.Domain.Entities.Company", "Company")
                        .WithMany("Buildings")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Condo.Domain.Entities.Condominium", "Condominium")
                        .WithMany("Buildings")
                        .HasForeignKey("CondominiumId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");

                    b.Navigation("Condominium");
                });

            modelBuilder.Entity("Condo.Domain.Entities.BuildingExpense", b =>
                {
                    b.HasOne("Condo.Domain.Entities.Building", "Building")
                        .WithMany("BuildingExpenses")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Condo.Domain.Entities.Company", "Company")
                        .WithMany("BuildingExpenses")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Condo.Domain.Entities.ExpensePeriod", "ExpensePeriod")
                        .WithMany("BuildingExpenses")
                        .HasForeignKey("ExpensePeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Condo.Domain.Entities.Unit", "TargetUnit")
                        .WithMany("BuildingExpenses")
                        .HasForeignKey("TargetUnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Building");

                    b.Navigation("Company");

                    b.Navigation("ExpensePeriod");

                    b.Navigation("TargetUnit");
                });

            modelBuilder.Entity("Condo.Domain.Entities.BuildingIncome", b =>
                {
                    b.HasOne("Condo.Domain.Entities.Building", "Building")
                        .WithMany("BuildingIncomes")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Condo.Domain.Entities.Company", "Company")
                        .WithMany("BuildingIncomes")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Condo.Domain.Entities.ExpensePeriod", "ExpensePeriod")
                        .WithMany("BuildingIncomes")
                        .HasForeignKey("ExpensePeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("Company");

                    b.Navigation("ExpensePeriod");
                });

            modelBuilder.Entity("Condo.Domain.Entities.Condominium", b =>
                {
                    b.HasOne("Condo.Domain.Entities.Company", "Company")
                        .WithMany("Condominiums")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Condo.Domain.Entities.ExpenseCharge", b =>
                {
                    b.HasOne("Condo.Domain.Entities.Company", "Company")
                        .WithMany("ExpenseCharges")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Condo.Domain.Entities.ExpensePeriod", "ExpensePeriod")
                        .WithMany("Charges")
                        .HasForeignKey("ExpensePeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Condo.Domain.Entities.BuildingExpense", "SourceBuildingExpense")
                        .WithMany("ExpenseCharges")
                        .HasForeignKey("SourceBuildingExpenseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Condo.Domain.Entities.ExpenseSettlement", "SourceSettlement")
                        .WithMany("ExpenseCharges")
                        .HasForeignKey("SourceSettlementId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Condo.Domain.Entities.Unit", "Unit")
                        .WithMany("ExpenseCharges")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("ExpensePeriod");

                    b.Navigation("SourceBuildingExpense");

                    b.Navigation("SourceSettlement");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Condo.Domain.Entities.ExpensePeriod", b =>
                {
                    b.HasOne("Condo.Domain.Entities.Building", "Building")
                        .WithMany("ExpensePeriods")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Condo.Domain.Entities.Company", "Company")
                        .WithMany("ExpensePeriods")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Condo.Domain.Entities.ExpenseSettlement", b =>
                {
                    b.HasOne("Condo.Domain.Entities.ApplicationUser", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Condo.Domain.Entities.Building", "Building")
                        .WithMany("ExpenseSettlements")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Condo.Domain.Entities.Company", "Company")
                        .WithMany("ExpenseSettlements")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Condo.Domain.Entities.ExpensePeriod", "ExpensePeriod")
                        .WithMany("ExpenseSettlements")
                        .HasForeignKey("ExpensePeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Condo.Domain.Entities.ApplicationUser", "GeneratedByUser")
                        .WithMany()
                        .HasForeignKey("GeneratedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Condo.Domain.Entities.ApplicationUser", "PublishedByUser")
                        .WithMany()
                        .HasForeignKey("PublishedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApprovedByUser");

                    b.Navigation("Building");

                    b.Navigation("Company");

                    b.Navigation("ExpensePeriod");

                    b.Navigation("GeneratedByUser");

                    b.Navigation("PublishedByUser");
                });

            modelBuilder.Entity("Condo.Domain.Entities.Payment", b =>
                {
                    b.HasOne("Condo.Domain.Entities.Company", "Company")
                        .WithMany("Payments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Condo.Domain.Entities.ExpensePeriod", "ExpensePeriod")
                        .WithMany("Payments")
                        .HasForeignKey("ExpensePeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Condo.Domain.Entities.Unit", "Unit")
                        .WithMany("Payments")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("ExpensePeriod");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Condo.Domain.Entities.Resident", b =>
                {
                    b.HasOne("Condo.Domain.Entities.Company", "Company")
                        .WithMany("Residents")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Condo.Domain.Entities.Unit", b =>
                {
                    b.HasOne("Condo.Domain.Entities.Building", "Building")
                        .WithMany("Units")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Condo.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Condo.Domain.Entities.UnitResident", b =>
                {
                    b.HasOne("Condo.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Condo.Domain.Entities.Resident", "Resident")
                        .WithMany("UnitResidents")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Condo.Domain.Entities.Unit", "Unit")
                        .WithMany("UnitResidents")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Resident");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Condo.Domain.Entities.UserBuildingAccess", b =>
                {
                    b.HasOne("Condo.Domain.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany("BuildingAccesses")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Condo.Domain.Entities.Building", "Building")
                        .WithMany("UserAccesses")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Building");
                });

            modelBuilder.Entity("Condo.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("BuildingAccesses");
                });

            modelBuilder.Entity("Condo.Domain.Entities.Building", b =>
                {
                    b.Navigation("BuildingExpenses");

                    b.Navigation("BuildingIncomes");

                    b.Navigation("ExpensePeriods");

                    b.Navigation("ExpenseSettlements");

                    b.Navigation("Units");

                    b.Navigation("UserAccesses");
                });

            modelBuilder.Entity("Condo.Domain.Entities.BuildingExpense", b =>
                {
                    b.Navigation("ExpenseCharges");
                });

            modelBuilder.Entity("Condo.Domain.Entities.Company", b =>
                {
                    b.Navigation("BuildingExpenses");

                    b.Navigation("BuildingIncomes");

                    b.Navigation("Buildings");

                    b.Navigation("Condominiums");

                    b.Navigation("ExpenseCharges");

                    b.Navigation("ExpensePeriods");

                    b.Navigation("ExpenseSettlements");

                    b.Navigation("Payments");

                    b.Navigation("Residents");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Condo.Domain.Entities.Condominium", b =>
                {
                    b.Navigation("Buildings");
                });

            modelBuilder.Entity("Condo.Domain.Entities.ExpensePeriod", b =>
                {
                    b.Navigation("BuildingExpenses");

                    b.Navigation("BuildingIncomes");

                    b.Navigation("Charges");

                    b.Navigation("ExpenseSettlements");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Condo.Domain.Entities.ExpenseSettlement", b =>
                {
                    b.Navigation("ExpenseCharges");
                });

            modelBuilder.Entity("Condo.Domain.Entities.Resident", b =>
                {
                    b.Navigation("UnitResidents");
                });

            modelBuilder.Entity("Condo.Domain.Entities.Unit", b =>
                {
                    b.Navigation("BuildingExpenses");

                    b.Navigation("ExpenseCharges");

                    b.Navigation("Payments");

                    b.Navigation("UnitResidents");
                });
#pragma warning restore 612, 618
        }
    }
}
